# Build context is kept small by .dockerignore.
#
# Dependencies are installed from a hash-pinned export of uv.lock, generated by
# scripts/build-service.sh in the ecosystem root. A bare `pip install <src>`
# resolves versions from PyPI at build time, which is how running images drifted
# past their own lockfile (measured: 15 of 23 packages on kryten-moderator).
FROM python:3.12

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential alembic.ini alembic \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --system --create-home --uid 1001 kryten

COPY pyproject.toml uv.lock README.md LICENSE requirements.lock.txt /tmp/kryten-economy/
COPY kryten_economy /tmp/kryten-economy/kryten_economy
COPY alembic.ini /tmp/kryten-economy/alembic.ini
COPY alembic /tmp/kryten-economy/alembic

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --require-hashes -r /tmp/kryten-economy/requirements.lock.txt \
    && pip install --no-cache-dir --no-deps /tmp/kryten-economy

# Fail the build rather than the deploy if the entry point is broken.
RUN python -c "import kryten_economy; print('kryten_economy', getattr(kryten_economy, '__version__', '?'))"

RUN mkdir -p /etc/kryten/kryten-economy /var/lib/kryten/kryten-economy \
    && chown -R kryten:kryten /etc/kryten /var/lib/kryten

USER kryten

ENTRYPOINT ["python -m kryten_economy"]
CMD ["--config", "/etc/kryten/kryten-economy/config.yaml"]
