"""Heist narrator — selects or generates narrative text for heist events.

Supports three modes controlled by ``HeistNarrativeConfig.mode``:

- **static** (default) — picks from the built-in library in
  ``heist_narratives`` plus any ``custom_*`` templates from config.
- **llm** — calls an OpenAI-compatible chat-completions endpoint to
  generate a bespoke heist story each time.
- **hybrid** — tries LLM first; falls back to static on timeout/error.
"""

from __future__ import annotations

import json
import logging
import random
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from . import heist_narratives

if TYPE_CHECKING:
    from .config import HeistNarrativeConfig


@dataclass
class HeistStory:
    """A complete set of narrative lines for one heist resolution.

    When generated by the LLM, *all four* text fields are populated in a
    single call so the scenario and outcome feel thematically connected.
    For the static path each field is drawn independently.
    """

    scenario: str = ""
    win: str = ""
    lose: str = ""
    push: str = ""


# ──────────────────────────────────────────────────────────────
#  Narrator
# ──────────────────────────────────────────────────────────────


class HeistNarrator:
    """Central narrator that all heist text goes through."""

    def __init__(
        self,
        config: HeistNarrativeConfig,
        logger: logging.Logger | None = None,
    ) -> None:
        self._cfg = config
        self._log = logger or logging.getLogger(__name__)

        # Merge built-in pools + any custom templates from config
        self._scenarios = list(heist_narratives.SCENARIOS) + list(config.custom_scenarios)
        self._win_lines = list(heist_narratives.WIN_LINES) + list(config.custom_win_lines)
        self._lose_lines = list(heist_narratives.LOSE_LINES) + list(config.custom_lose_lines)
        self._push_lines = list(heist_narratives.PUSH_LINES) + list(config.custom_push_lines)
        self._join_lines = list(heist_narratives.JOIN_LINES) + list(config.custom_join_lines)

        # Pre-generated LLM story cache (consumed once per heist)
        self._cached_story: HeistStory | None = None

    # ──────────────────────────────────────────────────────────
    #  Public pool access  (for external code that just needs pool length / list)
    # ──────────────────────────────────────────────────────────

    @property
    def scenarios(self) -> list[str]:
        return self._scenarios

    @property
    def win_lines(self) -> list[str]:
        return self._win_lines

    @property
    def lose_lines(self) -> list[str]:
        return self._lose_lines

    @property
    def push_lines(self) -> list[str]:
        return self._push_lines

    @property
    def join_lines(self) -> list[str]:
        return self._join_lines

    # ──────────────────────────────────────────────────────────
    #  Config hot-reload
    # ──────────────────────────────────────────────────────────

    def update_config(self, config: HeistNarrativeConfig) -> None:
        self._cfg = config
        self._scenarios = list(heist_narratives.SCENARIOS) + list(config.custom_scenarios)
        self._win_lines = list(heist_narratives.WIN_LINES) + list(config.custom_win_lines)
        self._lose_lines = list(heist_narratives.LOSE_LINES) + list(config.custom_lose_lines)
        self._push_lines = list(heist_narratives.PUSH_LINES) + list(config.custom_push_lines)
        self._join_lines = list(heist_narratives.JOIN_LINES) + list(config.custom_join_lines)

    # ──────────────────────────────────────────────────────────
    #  Static mode helpers
    # ──────────────────────────────────────────────────────────

    def _pick_static_scenario(self, user: str) -> str:
        return random.choice(self._scenarios).format(user=user)

    def _pick_static_win(self, payout: str, symbol: str, user: str) -> str:
        return random.choice(self._win_lines).format(
            payout=payout, symbol=symbol, user=user,
        )

    def _pick_static_lose(self, user: str, symbol: str) -> str:
        return random.choice(self._lose_lines).format(user=user, symbol=symbol)

    def _pick_static_push(self, user: str, symbol: str) -> str:
        return random.choice(self._push_lines).format(user=user, symbol=symbol)

    def _pick_static_join(self, user: str) -> str:
        return random.choice(self._join_lines).format(user=user)

    # ──────────────────────────────────────────────────────────
    #  LLM generation
    # ──────────────────────────────────────────────────────────

    async def _generate_llm_story(self) -> HeistStory | None:
        """Call an OpenAI-compatible endpoint to generate a full heist story.

        Returns ``None`` on any failure so callers can fall back to static.
        """
        llm_cfg = self._cfg.llm
        if not llm_cfg.endpoint:
            return None

        try:
            import aiohttp
        except ImportError:
            self._log.warning("aiohttp not installed — cannot use LLM narrator")
            return None

        headers: dict[str, str] = {"Content-Type": "application/json"}
        if llm_cfg.api_key:
            headers["Authorization"] = f"Bearer {llm_cfg.api_key}"

        payload = {
            "model": llm_cfg.model,
            "messages": [
                {"role": "system", "content": llm_cfg.system_prompt},
                {
                    "role": "user",
                    "content": (
                        "Generate a unique heist scenario for a chat-room game. "
                        "Keep each line under 280 characters. Use emoji freely. "
                        "Return ONLY valid JSON with keys: scenario, win, lose, push."
                    ),
                },
            ],
            "temperature": llm_cfg.temperature,
            "max_tokens": llm_cfg.max_tokens,
        }

        retries = llm_cfg.max_retries + 1
        for attempt in range(retries):
            try:
                timeout = aiohttp.ClientTimeout(total=llm_cfg.timeout_seconds)
                async with aiohttp.ClientSession(timeout=timeout) as session:
                    async with session.post(
                        llm_cfg.endpoint,
                        headers=headers,
                        json=payload,
                    ) as resp:
                        if resp.status != 200:
                            body = await resp.text()
                            self._log.warning(
                                "LLM narrator HTTP %s (attempt %d): %s",
                                resp.status, attempt + 1, body[:200],
                            )
                            continue
                        data = await resp.json()
            except Exception as exc:
                self._log.warning(
                    "LLM narrator error (attempt %d): %s", attempt + 1, exc,
                )
                continue

            # Parse the response
            try:
                content = data["choices"][0]["message"]["content"]
                # Strip markdown code fences if present
                content = content.strip()
                if content.startswith("```"):
                    content = content.split("\n", 1)[1] if "\n" in content else content[3:]
                if content.endswith("```"):
                    content = content[:-3]
                content = content.strip()

                story_data = json.loads(content)
                story = HeistStory(
                    scenario=story_data.get("scenario", ""),
                    win=story_data.get("win", ""),
                    lose=story_data.get("lose", ""),
                    push=story_data.get("push", ""),
                )
                # Validate we got something useful
                if story.scenario and story.win and story.lose:
                    self._log.debug("LLM narrator generated story successfully")
                    return story
                self._log.warning("LLM narrator returned incomplete story")
            except (json.JSONDecodeError, KeyError, IndexError) as exc:
                self._log.warning(
                    "LLM narrator parse error (attempt %d): %s", attempt + 1, exc,
                )
                continue

        return None

    # ──────────────────────────────────────────────────────────
    #  Heist resolution — pre-generate a full story when LLM is active
    # ──────────────────────────────────────────────────────────

    async def prepare_story(self) -> None:
        """Pre-generate an LLM story if the mode requires it.

        Call this once *before* ``get_scenario`` / ``get_win_line`` etc.
        so that a single LLM call produces a thematically consistent set.
        """
        self._cached_story = None
        mode = self._cfg.mode.lower()
        if mode in ("llm", "hybrid"):
            self._cached_story = await self._generate_llm_story()
            if self._cached_story is None and mode == "llm":
                self._log.warning(
                    "LLM narrator failed with mode='llm'; will use static fallback"
                )

    # ──────────────────────────────────────────────────────────
    #  Public API — called by GamblingEngine
    # ──────────────────────────────────────────────────────────

    def get_scenario(self, participants: list[str]) -> str:
        """Pick or use a cached scenario line.  {user} is filled in."""
        user = random.choice(participants)
        if self._cached_story and self._cached_story.scenario:
            return self._cached_story.scenario.format(
                user=user, payout="", symbol="",
            )
        return self._pick_static_scenario(user)

    def get_win_line(self, payout: str, symbol: str, user: str) -> str:
        if self._cached_story and self._cached_story.win:
            try:
                return self._cached_story.win.format(
                    payout=payout, symbol=symbol, user=user,
                )
            except KeyError:
                return self._cached_story.win
        return self._pick_static_win(payout, symbol, user)

    def get_lose_line(self, user: str, symbol: str) -> str:
        if self._cached_story and self._cached_story.lose:
            try:
                return self._cached_story.lose.format(
                    user=user, symbol=symbol, payout="",
                )
            except KeyError:
                return self._cached_story.lose
        return self._pick_static_lose(user, symbol)

    def get_push_line(self, user: str, symbol: str) -> str:
        if self._cached_story and self._cached_story.push:
            try:
                return self._cached_story.push.format(
                    user=user, symbol=symbol, payout="",
                )
            except KeyError:
                return self._cached_story.push
        return self._pick_static_push(user, symbol)

    def get_join_line(self, user: str) -> str:
        """Join lines always come from the static pool (no pre-generation)."""
        return self._pick_static_join(user)

    def consume_cached_story(self) -> None:
        """Clear the cached story after a heist resolves."""
        self._cached_story = None
